name: "setup-kotlin"
description: "Sets up the build environment for Kotlin Multiplatform projects"
inputs:
  java-version:
    description: "The version of Java to be provisioned"
    required: true
  github-token:
    description: "A GitHub token capable of cloning the repository"
    required: true
runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ inputs.github-token }}

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'build.gradle.kts') }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

    - name: Setup Gradle properties
      shell: bash
      run: |
        echo 'org.gradle.jvmargs = -Xmx4G -Dkotlin.daemon.jvm.options="-Xmx4G"' >> "${HOME}/.gradle/gradle.properties"
        echo 'org.gradle.daemon = false' >> "${HOME}/.gradle/gradle.properties"
