name: Test Kotlin project

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      java-version:
        required: false
        type: string
        default: "11"
      extra-flags:
        required: false
        type: string
        default: ""
    secrets:
      github-token:
        required: true

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github-token }}

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: |
          ./gradlew check ${{ inputs.extra-flags }}
