name: Test Kotlin project

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      java-version:
        required: false
        type: string
        default: "17"
      extra-flags:
        required: false
        type: string
        default: ""
    secrets:
      github-token:
        required: true

jobs:
  check:
    name: Run checks
    runs-on: ${{ inputs.runs-on }}
    if: github.event_name == 'pull_request'
    steps:
      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "$PR_TITLE" =~ RTK-[0-9]+ ]] && [[ ! "$PR_TITLE" =~ NOISSUE ]]; then
            echo "::error PR title must start with RTK followed by numbers (e.g., RTK-1234), or contain NOISSUE."
            exit 1
          fi

  test:
    name: Run tests
    needs: check
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Setup KMP
        uses: dyte-in/shared-workflows/setup-kotlin@main
        with:
          java-version: ${{ inputs.java-version }}
          github-token: ${{ secrets.github-token }}

      - name: Validate Swift formatting
        run: |
          swift_files=$(git ls-files | grep \\.swift$ | tr '\n' ' ')
          if [ -n "${swift_files}" ]; then
            swiftformat --verbose --strict ${swift_files}
          fi
      - name: Run tests
        run: |
          ./gradlew --no-daemon check ${{ inputs.extra-flags }}
