name: Test Kotlin project

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      java-version:
        required: false
        type: string
        default: "17"
      extra-flags:
        required: false
        type: string
        default: ""
    secrets:
      github-token:
        required: true

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Setup KMP
        uses: dyte-in/shared-workflows/setup-kotlin@main
        with:
          java-version: ${{ inputs.java-version }}
          github-token: ${{ secrets.github-token }}

      - name: Run tests
        run: |
          ./gradlew --no-daemon check ${{ inputs.extra-flags }}

      - name: Validate Swift formatting
        run: |
          if [[ -n $(git ls-files | grep \\.swift) ]]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew install swiftformat
            swiftformat --strict ./**/*.swift
          fi
